import { User } from '../App';

export const mockUsers: User[] = [
  { id: 2, name: 'Priya Sharma', role: 'admin', password: 'admin123', permissions: ['all'] },
];

// mockAnimals is no longer needed as data will be fetched from the backend.
// We can remove this array completely.
export const mockAnimals: any[] = [];

export const translations = {
  en: {
    zookeeper: 'Zookeeper',
    admin: 'Admin',
    vet: 'Vet Doctor',
    officer: 'Forest Officer',
    dashboard: 'Dashboard',
    myAnimals: 'My Animals',
    addLog: 'Add Log',
    viewProfile: 'View Profile',
    todaysTasks: "Today's Tasks",
    pendingLogs: 'Pending Logs',
    dailyLog: 'Daily Log',
    morningLog: 'Morning Log',
    eveningLog: 'Evening Log',
    observationPlaceholder: 'Enter daily observations here... (e.g., animal behavior, feeding, health notes)',
    submitObservation: 'Submit Text Observation',
    processing: 'Processing...',
    errorOccurred: 'An Error Occurred',
    processedData: 'Processed Data',
    date: 'Date',
    healthSummary: 'Health Summary',
    waterProvided: 'Clean Water Provided',
    enclosureClean: 'Enclosure Cleaned',
    normalBehavior: 'Normal Behavior',
    abnormalBehaviorDetails: 'Abnormal Behavior Details',
    enterObservation: 'Please enter an observation.',
    observationProcessedSuccess: 'Observation processed and saved!',
    processingError: 'Failed to process observation.',
    recorderStatus: 'Recorder Status',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    voiceLog: 'Voice Log',
    textLog: 'Text Log',
    healthAssessment: 'Health Assessment',
    mood: 'Mood',
    appetite: 'Appetite',
    movement: 'Movement',
    agitated: 'Agitated',
    calm: 'Calm',
    low: 'Low',
    high: 'High',
    slow: 'Slow',
    active: 'Active',
    injuriesReport: 'Injuries / Report',
    enterInjuries: 'Enter any injuries or specific observations...',
    submitVoiceLog: 'Submit Voice Log',
    submitFullLog: 'Submit Full Log',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    alerts: 'Alerts',
    settings: 'Settings',
    notifications: 'Notifications',
    logout: 'Logout',
    cancel: 'Cancel',
    sendAlert: 'Send Alert',
    sosAlert: 'SOS Alert',
    manageUsers: 'Manage Users',
    addAnimal: 'Add Animal',
    mediaUploads: 'Media Uploads',
    uploadImage: 'Upload Image',
    uploadVideo: 'Upload Video',
    transcribingAudio: 'Transcribing audio, please wait...',
    transcriptionSuccess: 'Audio transcribed successfully!',
    transcriptionError: 'Failed to transcribe audio.',
    shareWith: 'Share With',
    selectUsersToShare: 'Select individual users to share this log with',
    notifyVetDepartment: 'Notify Vet Department of this log',
    healthReports: 'Health Reports',
    voiceLogs: 'Voice Logs',

    // Voice Recording Questions - SECTION A: DAILY ANIMAL HEALTH
    question1: '1. Feeding & Drinking: How much feed did the animal consume (25%, 50%, 75%, 100%)? What quantity in kg/litres? Did it drink water normally? Any vomiting, diarrhoea, or digestion problems?',
    question2: '2. Health & Physical Condition: Any injury, swelling, wound, discharge, limping, or illness noticed? Did the animal appear weak, lethargic, or uncomfortable?',
    question3: '3. Behaviour & Activity: Was the animal more active, normal, less active, or very dull? Was it alert and responsive?',
    question4: '4. Reproductive Status: Any mating activity, heat signs, pregnancy, or birth observed?',
    question5: '5. Mortality / Critical Condition: Any death, serious injury, or critical illness observed?',
    question6: '6. Hygiene, Pest & Safety: Were flies, rodents, insects, or pests noticed? Any broken fence, sharp objects, or safety risks?',
    question7: '7. Additional Observations: Any unusual, important, or noteworthy observations?',

    // Voice Recording Questions - ENCLOSURE (GENERAL) REPORT
    question8: '1. Cleanliness & Waste: What time was the enclosure cleaned? Was waste removed properly and water area cleaned? If not, why?',
    question9: '2. Water & Sanitation: Was the water trough cleaned today? Is fresh and sufficient water available?',
    question10: '3. Fencing & Locking: Are all fences, cages, doors, and locks secure and functioning properly? Any issues?',
    question11: '4. Moat Condition: What is the moat condition - Dry, Wet, Partially Filled, or Not Applicable?',
    question12: '5. Pest Control: Were flies, mosquitoes, rodents, or insects noticed in the enclosure?',
    question13: '6. Staff Status: Was staff attendance complete today?',
    question14: '7. Final Safety: Were all cells, cages, and gates secured before closing?',
    question15: '8. Remarks: Any unusual observation, pending repair, or urgent action required?',
    question16: '9. Kraal / Night Shelter: Final check of the night shelter condition and security?',

  },
  hi: {
    zookeeper: 'चिड़ियाघर कीपर',
    admin: 'एडमिन',
    vet: 'पशु चिकित्सक',
    officer: 'वन अधिकारी',
    dashboard: 'डैशबोर्ड',
    myAnimals: 'मेरे जानवर',
    addLog: 'लॉग जोड़ें',
    viewProfile: 'प्रोफ़ाइल देखें',
    todaysTasks: 'आज के कार्य',
    pendingLogs: 'लंबित लॉग',
    dailyLog: 'दैनिक लॉग',
    morningLog: 'सुबह का लॉग',
    eveningLog: 'शाम का लॉग',
    observationPlaceholder: 'दैनिक अवलोकन यहाँ दर्ज करें... (जैसे, जानवर का व्यवहार, भोजन, स्वास्थ्य नोट्स)',
    submitObservation: 'टेक्स्ट अवलोकन सबमिट करें',
    processing: 'प्रोसेस हो रहा है...',
    errorOccurred: 'एक त्रुटि हुई',
    processedData: 'संसाधित डेटा',
    date: 'दिनांक',
    healthSummary: 'स्वास्थ्य सारांश',
    waterProvided: 'साफ पानी उपलब्ध',
    enclosureClean: 'बाड़ा साफ',
    normalBehavior: 'सामान्य व्यवहार',
    abnormalBehaviorDetails: 'असामान्य व्यवहार का विवरण',
    enterObservation: 'कृपया एक अवलोकन दर्ज करें।',
    observationProcessedSuccess: 'अवलोकन संसाधित और सहेजा गया!',
    processingError: 'अवलोकन संसाधित करने में विफल।',
    recorderStatus: 'रिकॉर्डर स्थिति',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    voiceLog: 'वॉयस लॉग',
    textLog: 'टेक्स्ट लॉग',
    healthAssessment: 'स्वास्थ्य मूल्यांकन',
    mood: 'मूड',
    appetite: 'भूख',
    movement: 'गति',
    agitated: 'उत्तेजित',
    calm: 'शांत',
    low: 'कम',
    high: 'उच्च',
    slow: 'धीमा',
    active: 'सक्रिय',
    injuriesReport: 'चोट / रिपोर्ट करें',
    enterInjuries: 'कोई चोट या विशिष्ट अवलोकन दर्ज करें...',
    submitVoiceLog: 'वॉयस लॉग सबमिट करें',
    excellent: 'उत्कृष्ट',
    good: 'अच्छा',
    fair: 'ठीक',
    poor: 'खराब',
    alerts: 'अलर्ट',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएं',
    logout: 'लॉगआउट',
    cancel: 'रद्द करें',
    sendAlert: 'अलर्ट भेजें',
    sosAlert: 'SOS अलर्ट',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    addAnimal: 'जानवर जोड़ें',
    mediaUploads: 'मीडिया अपलोड',
    uploadImage: 'छवि अपलोड करें',
    uploadVideo: 'वीडियो अपलोड करें',
    transcribingAudio: 'ऑडियो ट्रांसक्राइब हो रहा है, कृपया प्रतीक्षा करें...',
    transcriptionSuccess: 'ऑडियो सफलतापूर्वक ट्रांसक्राइब हो गया!',
    transcriptionError: 'ऑडियो ट्रांसक्राइब करने में विफल।',
    shareWith: 'साझा करें',
    selectUsersToShare: 'इस लॉग को साझा करने के लिए व्यक्तिगत उपयोगकर्ताओं का चयन करें',
    notifyVetDepartment: 'इस लॉग की पशु चिकित्सा विभाग को सूचित करें',
    healthReports: 'स्वास्थ्य रिपोर्ट',
    voiceLogs: 'वॉयस लॉग',


    // Voice Recording Questions - SECTION A: DAILY ANIMAL HEALTH (Hindi)
    question1: '1. भोजन और पानी: जानवर ने कितना भोजन खाया (25%, 50%, 75%, 100%)? कितनी मात्रा में (kg/लीटर)? क्या पानी सामान्य रूप से पिया? कोई उल्टी, दस्त, या पाचन समस्या?',
    question2: '2. स्वास्थ्य और शारीरिक स्थिति: कोई चोट, सूजन, घाव, स्राव, लंगड़ापन, या बीमारी दिखाई दी? क्या जानवर कमजोर, सुस्त, या असहज दिखाई दिया?',
    question3: '3. व्यवहार और गतिविधि: क्या जानवर अधिक सक्रिय, सामान्य, कम सक्रिय, या बहुत सुस्त था? क्या यह सतर्क और उत्तरदायी था?',
    question4: '4. प्रजनन स्थिति: कोई मेटिंग गतिविधि, हीट के संकेत, गर्भावस्था, या जन्म देखा गया?',
    question5: '5. मृत्यु / गंभीर स्थिति: कोई मृत्यु, गंभीर चोट, या गंभीर बीमारी देखी गई?',
    question6: '6. स्वच्छता, कीट और सुरक्षा: मक्खियां, चूहे, कीड़े, या कीट देखे गए? कोई टूटी बाड़, तेज वस्तु, या सुरक्षा जोखिम?',
    question7: '7. अतिरिक्त अवलोकन: कोई असामान्य, महत्वपूर्ण, या उल्लेखनीय अवलोकन?',

    // Voice Recording Questions - ENCLOSURE (GENERAL) REPORT (Hindi)
    question8: '1. सफाई और कचरा: बाड़ा किस समय साफ किया गया? क्या कचरा ठीक से हटाया गया और पानी का क्षेत्र साफ किया गया? यदि नहीं, तो क्यों?',
    question9: '2. पानी और स्वच्छता: क्या आज पानी का गर्त साफ किया गया? क्या ताजा और पर्याप्त पानी उपलब्ध है?',
    question10: '3. बाड़ और ताला: क्या सभी बाड़, पिंजरे, दरवाजे और ताले सुरक्षित और ठीक से काम कर रहे हैं? कोई समस्या?',
    question11: '4. खाई की स्थिति: खाई की स्थिति क्या है - सूखी, गीली, आंशिक रूप से भरी हुई, या लागू नहीं?',
    question12: '5. कीट नियंत्रण: क्या बाड़े में मक्खियां, मच्छर, चूहे, या कीड़े देखे गए?',
    question13: '6. कर्मचारी स्थिति: क्या आज कर्मचारियों की उपस्थिति पूर्ण थी?',
    question14: '7. अंतिम सुरक्षा: क्या बंद करने से पहले सभी कोशिकाएं, पिंजरे और गेट सुरक्षित किए गए?',
    question15: '8. टिप्पणियाँ: कोई असामान्य अवलोकन, लंबित मरम्मत, या तत्काल कार्रवाई आवश्यक?',
    question16: '9. क्राल / रात्रि आश्रय: रात्रि आश्रय की स्थिति और सुरक्षा की अंतिम जांच?',

  },
};
